apiVersion: v1
kind: Service
metadata:
  name: analytics-query-service
spec:
  selector:
    app: analytics-query-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
